---
__common_packages:
  - autoconf
  - bash-completion
  - bzip2
  - curl
  - diffutils
  - dnf
  - dos2unix
  # - firewalld
  - gawk
  - gcc
  - git
  - grep
  - gzip
  - htop
  - iftop
  - iotop
  - jq
  - less
  - make
  - nano
  - nmap
  - ntop
  - ntp
  - ntpdate
  - openssl
  - p7zip
  - pbzip2
  - pwgen
  - python2-dnf
  - tar
  - terminator
  - unzip
  - wget
  - whois
  - zip
  - unzip
