---

- name: "Create {{ gradle.parent_dir }} directory"
  file:
    path: "{{ parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- stat:
    path: "{{gradle.dir}}"
  register: gradle_dir

- debug:
  msg: "gradle_dir = {{ gradle_dir.stat.isdir }}"


- block:

  - name: get gradle tarball
    get_url:
      url: "{{gradle.url}}"
      dest:    "/tmp/{{gradle.file}}"

  - name: Unarchive gradle
    unarchive:
      src: "/tmp/{{gradle.file}}"
      dest: "{{parent_dir}}"
      copy: no

  when: gradle_dir.stat.isdir is not defined


- name: Remove old symlink
  file:
    path: "{{parent_dir}}/gradle"
    state: absent

- file:
    src: "{{gradle.dir}}"
    dest: "{{parent_dir}}/gradle"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: Remove old path configuration
  file:
    path: /etc/profile.d/gradle.sh
    state: absent
  become: yes

- name: "Configuring gradle home {{gradle.dir}} and add $PATH."
  template:
    src: gradle.sh.j2
    dest: /etc/profile.d/gradle.sh
    mode: 0644
  become: yes
