---

npm:
  version: 3.10.10
  packages_json_path: package.json.j2

  #  Install a specific version of a package.
  #  - name: jslint
  #    version: 0.9.3
  #  Install the latest stable release of a package.
  #  - name: node-sass
  #  This syntax also works.
  #  - node-sass
  packages:
    - jslint
    - eslint
    - gulp
    - nodemon
    - yo
